POST http://localhost:8080/
Content-Type: application/json

> {%
    client.global.set("link", response.body);
%}

###

GET {{link}}

###

POST http://localhost:8080/api/shorten
Content-Type: application/json

{
  "url": "https://practicum.yandex.ru"
}

> {%
    client.global.set("link", response.body);
%}
